import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'BUY TICKETS' }).click();
  await page.getByRole('button', { name: 'SELECT TICKET' }).first().click();
  await page.getByRole('button', { name: 'SELECT TICKET' }).first().click();
  await page.getByRole('complementary').getByRole('button', { name: 'SELECT DATE →' }).click();
  await page.getByRole('textbox', { name: 'VISIT DATE *' }).fill('2026-10-16');
  await page.getByLabel('ARRIVAL TIME *').selectOption('11:00');
  await page.getByRole('button', { name: 'ENTER DETAILS →' }).first().click();
  await page.getByRole('textbox', { name: 'FIRST NAME *' }).click();
  await page.getByRole('textbox', { name: 'FIRST NAME *' }).fill('sonal');
  await page.getByRole('textbox', { name: 'LAST NAME *' }).click();
  await page.getByRole('textbox', { name: 'LAST NAME *' }).fill('kumar');
  await page.getByRole('textbox', { name: 'EMAIL ADDRESS *' }).click();
  await page.getByRole('textbox', { name: 'EMAIL ADDRESS *' }).fill('s@gmail.com');
  await page.getByRole('textbox', { name: 'PHONE NUMBER *' }).click();
  await page.getByRole('textbox', { name: 'PHONE NUMBER *' }).fill('1234567890');
  await page.getByRole('textbox', { name: 'SPECIAL NOTES (optional)' }).click();
  await page.getByRole('textbox', { name: 'SPECIAL NOTES (optional)' }).fill('sdfghjk');
  await page.getByRole('button', { name: 'REVIEW ORDER →' }).first().click();
  await page.getByRole('button', { name: 'CONFIRM BOOKING →' }).first().click();
  await page1.goto('http://localhost:5173/admin/login');
  await page1.getByRole('textbox', { name: 'Email' }).click();
  await page1.getByRole('textbox', { name: 'Email' }).fill('admin@gmail.com');
  await page1.getByRole('textbox', { name: 'Password Show password' }).click();
  await page1.getByRole('textbox', { name: 'Password Show password' }).fill('admin123');
  await page1.getByRole('textbox', { name: 'Password Show password' }).press('Enter');
  await page1.getByRole('button', { name: 'Refresh' }).click();
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByRole('link', { name: 'View website' }).click();
  const page2 = await page2Promise;
  await page1.getByRole('link', { name: 'Bookings' }).click();
  await page1.getByText('☰BookingsRefreshView websiteSearchStatusAll statusesConfirmedChecked inNo-').click();
  await page1.getByText('☰BookingsRefreshView websiteSearchStatusAll statusesConfirmedChecked inNo-').click();
  await page1.getByLabel('StatusAll').selectOption('checked_in');
  await page1.getByLabel('StatusAll').selectOption('cancelled');
  await page1.locator('div').filter({ hasText: 'SearchStatusAll' }).nth(5).click();
  await page1.locator('div').filter({ hasText: 'SearchStatusAll' }).nth(3).click();
  await page1.getByRole('link', { name: 'Daily schedule' }).click();
  await page1.getByRole('link', { name: 'Daily schedule' }).click();
  await page1.getByRole('link', { name: 'Bookings' }).click();
  const downloadPromise = page1.waitForEvent('download');
  await page1.getByRole('button', { name: 'Export CSV' }).click();
  const download = await downloadPromise;
});